/***********************************************************************************************////////////
/***********************************************************************************************//////////
/**********************************    Author:  Mustafa Hafez    *******************************////////
/**********************************    Layer:   MCAL             *******************************//////
/**********************************    SWC:     PORT              *******************************////
/**********************************    Version: 1.0              *******************************///

#ifndef PORT_PRIVATE_H_
#define	PORT_PRIVATE_H_

#define CONC(b7,b6,b5,b4,b3,b2,b1,b0)			CONC_HELPER(b7,b6,b5,b4,b3,b2,b1,b0)

#define CONC_HELPER(b7,b6,b5,b4,b3,b2,b1,b0)	0b##b0##b1##b2##b3##b4##b5##b6##b7

#define PORTA_DIR								CONC(PORTA_PIN0_DIR,PORTA_PIN1_DIR,PORTA_PIN2_DIR,PORTA_PIN3_DIR,PORTA_PIN4_DIR,PORTA_PIN5_DIR,PORTA_PIN6_DIR,PORTA_PIN7_DIR)
#define PORTB_DIR								CONC(PORTB_PIN0_DIR,PORTB_PIN1_DIR,PORTB_PIN2_DIR,PORTB_PIN3_DIR,PORTB_PIN4_DIR,PORTB_PIN5_DIR,PORTB_PIN6_DIR,PORTB_PIN7_DIR)
#define PORTC_DIR								CONC(PORTC_PIN0_DIR,PORTC_PIN1_DIR,PORTC_PIN2_DIR,PORTC_PIN3_DIR,PORTC_PIN4_DIR,PORTC_PIN5_DIR,PORTC_PIN6_DIR,PORTC_PIN7_DIR)
#define PORTD_DIR								CONC(PORTD_PIN0_DIR,PORTD_PIN1_DIR,PORTD_PIN2_DIR,PORTD_PIN3_DIR,PORTD_PIN4_DIR,PORTD_PIN5_DIR,PORTD_PIN6_DIR,PORTD_PIN7_DIR)


#define PORTA_INIT_VALUE						CONC(PORTA_PIN0_INIT_VALUE,PORTA_PIN1_INIT_VALUE,PORTA_PIN2_INIT_VALUE,PORTA_PIN3_INIT_VALUE,PORTA_PIN4_INIT_VALUE,PORTA_PIN5_INIT_VALUE,PORTA_PIN6_INIT_VALUE,PORTA_PIN7_INIT_VALUE)
#define PORTB_INIT_VALUE						CONC(PORTB_PIN0_INIT_VALUE,PORTB_PIN1_INIT_VALUE,PORTB_PIN2_INIT_VALUE,PORTB_PIN3_INIT_VALUE,PORTB_PIN4_INIT_VALUE,PORTB_PIN5_INIT_VALUE,PORTB_PIN6_INIT_VALUE,PORTB_PIN7_INIT_VALUE)
#define PORTC_INIT_VALUE						CONC(PORTC_PIN0_INIT_VALUE,PORTC_PIN1_INIT_VALUE,PORTC_PIN2_INIT_VALUE,PORTC_PIN3_INIT_VALUE,PORTC_PIN4_INIT_VALUE,PORTC_PIN5_INIT_VALUE,PORTC_PIN6_INIT_VALUE,PORTC_PIN7_INIT_VALUE)
#define PORTD_INIT_VALUE						CONC(PORTD_PIN0_INIT_VALUE,PORTD_PIN1_INIT_VALUE,PORTD_PIN2_INIT_VALUE,PORTD_PIN3_INIT_VALUE,PORTD_PIN4_INIT_VALUE,PORTD_PIN5_INIT_VALUE,PORTD_PIN6_INIT_VALUE,PORTD_PIN7_INIT_VALUE)


#endif
